version: "3.8"

services:
  # Laravel backend
  backend:
    build: ../backend
    container_name: laravel_app
    volumes:
      - ../backend:/var/www/html
    expose:
      - 9000

  # Next.js frontend
  frontend:
    build: ../frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
  postgres:
    image: postgres:15
    container_name: pjweb_postgres
    environment:
      - POSTGRES_DB=pjweb
      - POSTGRES_USER=pjweb
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Nếu không muốn mở port ra host, bỏ dòng ports
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:

   