services:
  # Laravel backend (PHP-FPM)
  backend:
    build: ../backend
    container_name: laravel_app
    volumes:
      - ../backend:/var/www/html
    expose:
      - 9000
    depends_on:
      - postgres

  # Nginx gateway duy nhất
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  # Database PostgreSQL
  postgres:
    image: postgres:15
    container_name: pjweb_postgres
    environment:
      - POSTGRES_DB=pjweb
      - POSTGRES_USER=pjweb
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # pgAdmin (giao diện web quản lý DB)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
